"""initial schema

Revision ID: 3469db1ee2f6
Revises: 
Create Date: 2026-07-01 17:14:51.625402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3469db1ee2f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('supplier_slug', sa.String(length=128), nullable=False),
    sa.Column('products', sa.Text(), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('importer_version', sa.String(length=32), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_supplier_slug'), 'snapshots', ['supplier_slug'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_slug'), 'suppliers', ['slug'], unique=True)
    op.create_table('change_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('supplier_slug', sa.String(length=128), nullable=False),
    sa.Column('source_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('target_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('changes_json', sa.Text(), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.Column('report_text', sa.Text(), nullable=False),
    sa.Column('total_changes', sa.Integer(), nullable=False),
    sa.Column('major_count', sa.Integer(), nullable=False),
    sa.Column('normal_count', sa.Integer(), nullable=False),
    sa.Column('minor_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['snapshots.id'], ),
    sa.ForeignKeyConstraint(['target_snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_sets_supplier_slug'), 'change_sets', ['supplier_slug'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=512), nullable=True),
    sa.Column('collection', sa.String(length=256), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('compare_at_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_external_id'), 'products', ['external_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('alt_text', sa.String(length=512), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=256), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variants')
    op.drop_table('images')
    op.drop_index(op.f('ix_products_external_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_change_sets_supplier_slug'), table_name='change_sets')
    op.drop_table('change_sets')
    op.drop_index(op.f('ix_suppliers_slug'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_snapshots_supplier_slug'), table_name='snapshots')
    op.drop_table('snapshots')
    # ### end Alembic commands ###
